export const skillsArray = [
  { id: 1, skill: "Semantic & accessible HTML" },
  { id: 2, skill: "React Router" },
  { id: 3, skill: "Promises, Async/Await" },
  { id: 4, skill: "Responsive Web Design" },
  { id: 5, skill: "Redux-Saga" },
  { id: 6, skill: "GitHub Pull Requests & Review" },
  { id: 7, skill: "Teamwork" },
  { id: 8, skill: "Redux (Toolkit)" },
  { id: 9, skill: "Trello" },
  { id: 10, skill: "Markdown" },
  { id: 11, skill: "React Hooks" },
  { id: 12, skill: "Scrum" },
  { id: 13, skill: "Immutability" },
  { id: 14, skill: "Error handling" },
  { id: 15, skill: "NPM" },
  { id: 16, skill: "CSS BEM convention" },
  { id: 17, skill: "Working with API (fetch, axios)" },
  { id: 18, skill: "React" },
  { id: 19, skill: "CSS Grid" },
  { id: 20, skill: "JavaScript - ES6+" },
  { id: 21, skill: "Git" },
  { id: 22, skill: "CSS Flexbox" },
];

export const learningGoalsArray = [
  { id: 1, skill: "TypeScript" },
  { id: 2, skill: "Tailwind CSS" },
  { id: 3, skill: "Next.js" },
];
